version: "3.3"

services:
  bot:
    container_name: snbot
    depends_on:
      - redis-cache
    build:
      context: .
      dockerfile: Dockerfile
    image: snbot
    ports:
      - "8079:8079"
    environment:
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ReDiSsUpErPaSsWoRd

  redis-cache:
    image: redis:7.0.11
    container_name: redis-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ReDiSsUpErPaSsWoRd
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
