server:
  port: 8079

bot:
  name: snbot37_bot
  token: 6281761756:AAFXKwU6EZp0I9Lq-MrP2YBIcxeTZ0XDhO0
  api: http://81.177.6.228:8086/api/v1/

spring:
  kafka:
    consumer:
      topic-name: topic-1
      group-id: group-1
      bootstrap-servers: 81.177.6.228:9092
      properties:
        spring.json.trusted.packages: "*"
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: true
      client-id: example
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      client-id: example
      retries: 2
    listener:
      poll-timeout: 1800000
      concurrency: 1
